# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app/backend

COPY backend/package*.json ./
RUN npm install

COPY backend/. .

RUN npm run build

# Stage 2: Runtime
FROM node:18-alpine

WORKDIR /app/backend

COPY --from=builder /app/backend/dist ./dist
COPY --from=builder /app/backend/node_modules ./node_modules
COPY --from=builder /app/backend/.env.example ./.env

CMD ["node", "dist/main"]
